# name for this workflow
# on - what event watch for which when code changes in main/master in container dir
# working-directory - execution env which dir to run commands 
# want a Linux based VM
# steps - commands we want to execute and take our code and load into this VM
name: deploy-container
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'packages/container/**'
defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      # deploy to AWS S3 bucket
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    